#!/bin/bash

# Setting up timezone and clock
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc

# Language
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/^#sv_SE.UTF-8 UTF-8/sv_SE.UTF-8 UTF-8/' /etc/locale.gen
#echo "en_US.UTF-8 UTF-8" | tee -a /etc/locale.gen >/dev/null
#echo "sv_SE.UTF-8 UTF-8" | tee -a /etc/locale.gen >/dev/null
locale-gen

echo "LANG=C.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_NUMERIC=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_TIME=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_MONETARY=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_PAPER=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null
echo "LC_MEASUREMENT=sv_SE.UTF-8" | tee -a /etc/locale.conf >/dev/null

# Setting up keymap and terminal font
echo "KEYMAP=sv-latin1" | tee -a /etc/vconsole.conf >/dev/null
echo "FONT=ter-124n" | tee -a /etc/vconsole.conf >/dev/null

# Setting up Hostname and Network
echo "arch-desktop" | tee -a /etc/hostname >/dev/null

echo "127.0.0.1  localhost" /etc/hosts
echo "::  localhost" /etc/hosts
echo "127.0.1.1  arch-desktop" /etc/hosts

# Configuring /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf
sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf
sed -i 's/^#[multilib]/[multilib]/' /etc/pacman.conf
sed -i 's|^#Include = /etc/pacman.d/mirrorlist|Include = /etc/pacman.d/mirrorlist|' /etc/pacman.conf

# Installing and Configuring Boot Manager
pacman -S --noconfirm efibootmgr

bootctl --path=/boot install

touch /boot/loader/entries/arch.conf
echo "title Arch Linux" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "linux vmlinuz-linux" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "initrd initramfs-linux.img" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "options" | tee -a /boot/loader/entries/arch.conf >/dev/null
echo "options root=$(blkid | grep '/dev/nvme1n1p3' | cut -d' ' -f2 | sed 's/"//g') rw splash lsm=landlock,lockdown,yama,integrity,apparmor,bpf" | tee -a /boot/loader/entries/arch.conf >/dev/null
#blkid | tee -a /boot/loader/entries/arch.conf >/dev/null
#echo "rw splash lsm=landlock,lockdown,yama,integrity,apparmor,bpf" | tee -a /boot/loader/entries/arch.conf >/dev/null

echo "default arch" > /boot/loader/loader.conf

nano /boot/loader/entries/arch.conf
nano /boot/loader/loader.conf

# Adding users and setting passwords
passwd
useradd -m -G wheel modda
passwd modda

# Desktop Environment
#pacman -S --noconfirm gdm gnome gnome-terminal networkmanager firefox

# Applications
#pacman -S --noconfirm steam lutris wine wine-mono wine-gecko spotify-launcher fish fuse vlc flatpak snapd

# Office
#pacman -S --noconfirm libreoffice-fresh-sv

# AMD GPU Drivers
#pacman -S --noconfirm mesa lib32-mesa libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau vulkan-radeon lib32-vulkan-radeon 

# All in one
#pacman -S --noconfirm 

systemctl enable NetworkManager
systemctl enable gdm
