#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/nvme1n1p1
mkswap /dev/nvme1n1p2
swapon /dev/nvme1n1p2
mkfs.ext4 /dev/nvme1n1p3
mkfs.ext4 /dev/nvme1n1p4

# Mounting root partition
mount /dev/nvme1n1p3 /mnt

# Setting up boot folder
mkdir /mnt/boot
mount /dev/nvme1n1p1 /boot

# Creating home directory
mkdir /mnt/home
mount /dev/nvme1n1p4 /mnt/home

# Adding to pacman.conf
echo "ParallelDownloads = 10" | tee -a /etc/pacman.conf

# Installing base system
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt
mv user /mnt

# Chroot into new system
arch-chroot /mnt
